fuliangmart/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("martApp.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

martApp/urls.py
from django import views
from django.urls import path, include
from martApp.views import save_checkout_info, add_to_cart, add_to_wishlist, ajax_add_review, ajax_contact_form, cart_view, category_list_view, category_product_list__view, checkout, customer_dashboard, delete_item_from_cart, filter_product, index, make_address_default, order_detail, payment_completed_view, payment_failed_view, product_detail_view, product_list_view, remove_wishlist, search_view, tag_list, update_cart, vendor_detail_view, vendor_list_view, wishlist_view, contact, about_us, purchase_guide, privacy_policy, terms_of_service

app_name = "martApp"

urlpatterns = [

    # Homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("product/<pid>/", product_detail_view, name="product-detail"),
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list__view, name="category-product-list"),
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),

    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),
    
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),
    path("search/", search_view, name="search"),
    path("filter-products/", filter_product, name="filter-product"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),
    path("update-cart/", update_cart, name="update-cart"),
    # path("api/create_checkout_session/<oid>/", create_checkout_session, name="api_checkout_session"),
    path("save_checkout_info/", save_checkout_info, name="save_checkout_info"),
    path("checkout/<oid>/", checkout, name="checkout"),
    # path('paypal/', include('paypal.standard.ipn.urls')),
    path("payment-completed/<oid>/", payment_completed_view, name="payment-completed"),
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    path("dashboard/", customer_dashboard, name="dashboard"),
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),
    path("make-default-address/", make_address_default, name="make-default-address"),
    path("wishlist/", wishlist_view, name="wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),
    path("remove-from-wishlist/", remove_wishlist, name="remove-from-wishlist"),
    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),
    path("about_us/", about_us, name="about_us"),
    path("purchase_guide/", purchase_guide, name="purchase_guide"),
    path("privacy_policy/", privacy_policy, name="privacy_policy"),
    path("terms_of_service/", terms_of_service, name="terms_of_service"),
]

templates/core/cart.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main" id="cart-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="/" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Cart
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Your Cart</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> products in your cart</h6>
                    </div>
                </div>
            </div>
            <form action="{% url 'martApp:save_checkout_info' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-8">
                        <div class="table-responsive shopping-summery">
                            <table class="table table-wishlist">
                                <thead>
                                    <tr class="main-heading">
                                        
                                        <th scope="col">Product</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Unit Price</th>
                                        <th scope="col" class="text-center">Quantity</th>
                                        <th scope="col">Subtotal</th>
                                        <th scope="col" class="">Refresh</th>
                                        <th scope="col" class="end">Remove</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product_id, item in cart_data.items %}
                                    <tr class="pt-30">
                                        <td class="image product-thumbnail pt-40"><img src="{{ item.image }}" alt="#"></td>
                                        <td class="product-des product-name">
                                            <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'martApp:product-detail' item.pid %}">{{ item.title }}</a></h6>
                                        
                                        </td>
                                        <td class="price" data-title="Price">
                                            <h4 class="text-body">${{item.price|floatformat:2}}</h4>
                                        </td>
                                        <td class="text-center detail-info" data-title="Stock">
                                            <div class="mr-15">
                                                <input type="number" placeholder="Qty" class="w-25 product-qty-{{ product_id }}"  name="" value="{{ item.qty }}" id="">
                                            </div>
                                        </td>
                                        <td class="price" data-title="Price">
                                            <h4 class="text-brand">${% widthratio item.price 1 item.qty %} </h4>
                                        </td>
                                        <td class="action text-center" data-title="Remove"><a style="border: none; background: none;"  class="text-body update-product" data-product="{{ product_id }}"><i class="fi-rs-refresh"></i></a></td>
                                        <td class="action text-center" data-title="Remove"><a style="border: none; background: none;"  class="text-body delete-product" data-product="{{ product_id }}"><i class="fi-rs-trash"></i></a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                            <div class="row mt-4">
                                <h4 class="mb-30">Bio Data</h4>
                                <div class="row">
                                    <div class="form-group col-lg-12">
                                        <label for="">Full Name</label>
                                        <input type="text" required="" name="full_name" value="{{request.user.username|title}}" placeholder="Full Name">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">Email</label>
                                        <input type="text" required="" name="email"  placeholder="mobile *" value="{{request.user.email}}">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">Mobile</label>
                                        <input type="text" name="mobile" value="{{request.user.profile.phone}}" required="" placeholder="Address *">
                                    </div>
                                </div>
                                <h4 class="mb-30">Shipping Details</h4>
                                <div class="row">
                                    <div class="form-group col-lg-6">
                                        <label for="">Address</label>
                                        <input type="text" name="address" value="" placeholder="Address">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">City</label>
                                        <input type="text" name="city"  placeholder="City *" value="">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">State</label>
                                        <input type="text" name="state" value="" placeholder="State *">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">Country</label>
                                        <input type="text" name="country" value="" placeholder="Country *">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="border p-md-4 cart-totals ml-30">
                            <div class="table-responsive">
                                <div>
                                    <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Tax</p>
                                        <p>$0</p>
                                    </div>
                                    <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Shipping</p>
                                        <p>$0</p>
                                    </div>
                                    <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Discount</p>
                                        <p>$0</p>
                                    </div>
                                    
                                    <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Total</p>
                                        <p>${{cart_total_amount}}</p>
                                    </div>
                                </div>
                            </div>
                            {% if totalcartitems %}
                                <button type=submit" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></button>
                            {% endif %}                    
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

templates/core/category-product-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main">
        <div class="page-header mt-30 mb-50">
            <div class="container">
                <div class="archive-header">
                    <div class="row align-items-center">
                        <div class="col-xl-3">
                            <h1 class="mb-15">{{category.title}}</h1>
                            <div class="breadcrumb">
                                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                                <span></span> Shop <span></span> {{category.title}}
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="container mb-30">
            <div class="row">
                <div class="col-12">
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p>We found <strong class="text-brand">{{products.count}}</strong> item{{products.count|pluralize}} for you!</p>
                        </div>
                        <div class="sort-by-product-area">
                            <div class="sort-by-cover mr-10">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps"></i>Show:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">50</a></li>
                                        <li><a href="#">100</a></li>
                                        <li><a href="#">150</a></li>
                                        <li><a href="#">200</a></li>
                                        <li><a href="#">All</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sort-by-cover">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">Featured</a></li>
                                        <li><a href="#">Price: Low to High</a></li>
                                        <li><a href="#">Price: High to Low</a></li>
                                        <li><a href="#">Release Date</a></li>
                                        <li><a href="#">Avg. Rating</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row product-grid">
                        {% for p in products %}
                        <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                            <div class="product-cart-wrap mb-30">
                                <div class="product-img-action-wrap">
                                    <div class="product-img product-img-zoom">
                                        <a href="{% url 'martApp:product-detail' p.pid %}">
                                            <img class="default-img" src="{{ p.image.url }}" alt="" style="height: 280px; width: 280px; object-fit: cover;"   />
                                            <img class="hover-img" src="{{ p.image.url }}" alt=""  style="height: 280px; width: 280px; object-fit: cover;"  />

                                        </a>
                                    </div>
                                    <div class="product-action-1">
                                        <a aria-label="Add To Wishlist"  class="action-btn add-to-wishlist" data-product-item="{{p.id}}"><i class="fi-rs-heart"></i></a>
                                        <!-- <a aria-label="Compare" class="action-btn" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a> -->
                                        <a href="{% url 'martApp:product-detail' p.pid %}" class="action-btn"><i class="fi-rs-eye"></i></a>
                                    </div>
                                    <div class="product-badges product-badges-position product-badges-mrg">
                                        <span class="hot">-{{p.get_precentage|floatformat:0}}%</span>
                                    </div>
                                </div>
                                <div class="product-content-wrap">
                                    <div class="product-category">
                                        <a href="{% url 'martApp:product-detail' p.pid %}">{{ p.category.title }}</a>
                                    </div>
                                    <h2><a href="shop-product-right.html">{{ p.title }}</a></h2>
                                    <div class="product-rate-cover">
                                        <i class="fas fa-star text-warning"></i>
                                        <span class="font-small ml-5 text-muted"> ({{ p.reviews.all.count }})</span>

                                    </div>
                                    <div>
                                        <span class="font-small text-muted">By <a href="{% url 'martApp:vendor-detail' p.vendor.vid %}">{{p.vendor.title}}</a></span>
                                    </div>
                                    <div class="product-card-bottom">
                                        <div class="product-price">
                                            <span>$</span> <span class="current-product-price-{{ p.id }}">{{p.price}}</span>
                                            <span class="old-price">${{p.old_price}}</span>
                                        </div>
                                        <div class="add-cart">
                                            <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ p.id }}">
                                            <input type="hidden" class="product-pid-{{ p.id }}" value="{{ p.pid }}">
                                            <input type="hidden" class="product-image-{{ p.id }}" value="{{ p.image.url }}">
                                            <input type="hidden" class="product-id-{{ p.id }}" value="{{ p.id }}">
                                            <input type="hidden" class="product-title-{{ p.id }}" value="{{ p.title }}">
                                            <div class="d-flex">
                                                <button class="add add-to-cart-btn" data-index="{{ p.id }}" style="border: none;" id="add-to-cart-btn"><i class="fi-rs-shopping-cart mr-5"></i>Add</button>
                                                <button style="border: none; background: none;" class="add-to-wishlist" data-product-item="{{p.id}}"><i class="fi-rs-heart" style="fill: aqua;"></i></button>
                                            </div>
                                            <!-- <button class="add add-to-cart-btn" data-index="{{ p.id }}" style="border: none;" id="add-to-cart-btn"><i class="fi-rs-shopping-cart mr-5"></i>Add</button> -->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!--product grid-->
                    <!-- <div class="pagination-area mt-20 mb-20">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-start">
                                <li class="page-item">
                                    <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item active"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                <li class="page-item"><a class="page-link" href="#">6</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                                </li>
                            </ul>
                        </nav>
                    </div> -->
                </div>
            </div>
        </div>
    </main>
   
{% endblock content %}

templates/core/checkout.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'martApp:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop <span></span> Checkout
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Checkout</h1>
                    <div class="d-flex justify-content-between"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-7">
                    <div class="row">
                        {% for o in order_items %}
                        <div class="col-lg-6 mb-2">
                            <div class="card" style="max-width: 540px;">
                                <div class="row g-0">
                                    <div class="col-sm-4">
                                        <img src="{{o.image}}" style="width: 100%; height: 100%; object-fit: cover;" class="rounded-start" alt="Card image" />
                                    </div>
                                    <div class="col-sm-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{o.item}}</h5>
                                            <p class="card-text fs-sm">Qty: {{ o.qty }}</p>
                                            <p class="card-text fs-sm">Price: ${{ o.price }}</p>
                                            <p class="card-text fs-sm">Total: ${{ o.total }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="border cart-totals mb-50">
                        <div class="d-flex align-items-end justify-content-between mb-30">
                            <h4>Order Summary</h4>
                        </div>

                        <div>
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Tax</p>
                                <p>$0</p>
                            </div>
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Shipping</p>
                                <p>$0</p>
                            </div>
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Discount</p>
                                <p>${{ order.saved }}</p>
                            </div>
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Total</p>
                                <p>${{order.price}}</p>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-50">
                        <div class="col-lg-12">
                            <form method="POST" class="apply-coupon">
                                {% csrf_token %}
                                <input type="text" name="code" placeholder="Enter Coupon Code..." />
                                <button class="btn btn-md" type="submit" name="login">Apply</button>
                            </form>
                        </div>
                    </div>
                    <form action="{% url 'martApp:payment-completed' oid=order.oid %}" method="POST">
                        {% csrf_token %}
                        <!-- <button class="btn w-100" style="background-color: blueviolet">Place Order</button> -->
                        <button type="submit" class="btn w-100" id="checkout-button" style="background-color: blueviolet;">Place Order</button>
                    </form>
                    <div id="paypal-button-container" class="mt-3"></div>
                </div>
            </div>
        </div>
    </main>

    <script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://js.stripe.com/v3/"></script>

    <!-- <script>
        paypal
            .Buttons({
                createOrder: function (data, actions) {
                    return actions.order.create({
                        purchase_units: [
                            {
                                amount: {
                                    value: "{{order.price}}",
                                },
                            },
                        ],
                    });
                },

                onApprove: function (data, actions) {
                    return actions.order.capture().then(function (Detail) {
                        console.log(Detail);
                        if (Detail.status === "COMPLETED") {
                            window.location.href = `/payment-completed/{{ order.oid }}/?status=${Detail.status}`;
                        }
                    });
                },
            })
            .render("#paypal-button-container");
    </script>

    <script>
        var stripe = Stripe("{{stripe_publishable_key}}");
        var checkoutButton = document.getElementById("checkout-button");

        try {
            checkoutButton.addEventListener("click", function () {
            var email = "{{booking.email}}";

            checkoutButton.innerHTML = "Processing <i class='fas fa-spinner fa-spin'></i>";

            fetch("/api/create_checkout_session/{{order.oid}}/", {
                method: "POST",
                body: JSON.stringify({ email: email }),
            })
                .then(function (response) {
                    console.log(response);
                    console.log(stripe);
                    return response.json();
                })
                .then(function (session) {
                    return stripe.redirectToCheckout({ sessionId: session.sessionId });
                })
                .then(function (result) {
                    if (result.error) {
                        alert(result.error.message);
                    }
                })
                .catch(function (error) {
                    console.log("Error: ", error);
                });
        });
    
    
        } catch (error) {
            console.log(error);
        }
    </script> -->


{% endblock content %}
    

templates/core/payment-failed.html

{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
<div class="row justify-content-center pt-lg-4 text-center" style="margin-bottom: 200px; margin-top: 100px;">
    <div class="col-lg-5 col-md-7 col-sm-9">
        <h1 class="display-404 py-lg-3">Payment Failed</h1>
        <h2 class="h3 mb-4">Your order could not be placed, try again.</h2>
        <p class="fs-md mb-4">
        <a href="#">Contact us</a> if you have any issue or question
        </p>
    </div>
</div>
{% endblock content %}